version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=jolaushy
      - POSTGRES_PASSWORD=jolaushy
      - POSTGRES_DB=jolaushy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_URL=postgresql+psycopg2://jolaushy:jolaushy@postgres:5432/jolaushy
      - GROQ_API_KEY=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
    depends_on:
      - redis
      - postgres
    volumes:
      - ./src:/app/src
    command: uvicorn app:app --host 0.0.0.0 --port 8080 --reload

  celery_worker:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_URL=postgresql+psycopg2://jolaushy:jolaushy@postgres:5432/jolaushy
      - GROQ_API_KEY=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
    depends_on:
      - redis
      - postgres
    volumes:
      - ./src:/app/src
    command: celery -A celery_app worker --loglevel=info

  celery_beat:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_URL=postgresql+psycopg2://jolaushy:jolaushy@postgres:5432/jolaushy
      - GROQ_API_KEY=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
    depends_on:
      - redis
      - postgres
    volumes:
      - ./src:/app/src
    command: celery -A celery_app beat --loglevel=info

volumes:
  redis_data:
  postgres_data: 